# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Kerr
email: jack775544@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jack Kerr - Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jack775544.github.io" # the base hostname & protocol for your site
twitter_username: jack775544
github_username:  jack775544

# Build settings
markdown: kramdown
